import { MigrationInterface, QueryRunner } from "typeorm";

export class NewMigration1779693932940 implements MigrationInterface {
    name = 'NewMigration1779693932940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "createdOnByUserId" character varying, "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedByUserId" character varying, "deleteAt" TIMESTAMP, "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying, "lastName" character varying, "avatar" character varying, "phone" character varying, "location" character varying, "isAdmin" boolean NOT NULL DEFAULT false, "verify" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_LOCATION" ON "users" ("location") `);
        await queryRunner.query(`CREATE TABLE "medias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "createdOnByUserId" character varying, "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedByUserId" character varying, "deleteAt" TIMESTAMP, "name" character varying NOT NULL, "url" character varying NOT NULL, "type" integer NOT NULL DEFAULT '0', "status" integer NOT NULL DEFAULT '1', "attributes" text, "userId" uuid, "propertyId" integer, CONSTRAINT "PK_f27321557a66cd4fae9bc1ed6e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "owners" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "image" character varying NOT NULL, "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_42838282f2e6b216301a70b02d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."properties_type_enum" AS ENUM('villa', 'apartment', 'house', 'cabin', 'loft')`);
        await queryRunner.query(`CREATE TABLE "properties" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "price" numeric(12,2) NOT NULL, "pricePerMonth" numeric(12,2), "beds" integer, "baths" numeric(3,1), "sqft" integer NOT NULL, "type" "public"."properties_type_enum" NOT NULL, "location" character varying NOT NULL, "image" character varying NOT NULL, "rating" numeric(3,2) NOT NULL DEFAULT '0', "reviewsCount" integer NOT NULL DEFAULT '0', "amenities" text, "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), "owner_id" integer, CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PROPERTIES_TITLE" ON "properties" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROPERTIES_PRICE" ON "properties" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROPERTIES_PRICE_PER_MONTH" ON "properties" ("pricePerMonth") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROPERTIES_TYPE" ON "properties" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROPERTIES_LOCATION" ON "properties" ("location") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "createdOnByUserId" character varying, "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedByUserId" character varying, "deleteAt" TIMESTAMP, "rating" integer NOT NULL, "comment" text NOT NULL, "property_id" integer, "user_id" uuid, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "pricePerMonth" numeric(10,2) NOT NULL DEFAULT '0', "features" text, CONSTRAINT "UQ_95f7ef3fc4c31a3545b4d825dd4" UNIQUE ("code"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'active', "currentPeriodEnd" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "planId" uuid, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_SUBSCRIPTIONS_USER_ID" ON "subscriptions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_SUBSCRIPTIONS_STATUS" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE TABLE "reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_acd6ec48b54150b1736d0b454b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_RESET_TOKENS_USER_ID" ON "reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_RESET_TOKENS_TOKEN_HASH" ON "reset_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "rental_post_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "rentalPostId" uuid, CONSTRAINT "PK_93a7f12722a2368d8f01ffb4526" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POST_IMAGES_POST_ID" ON "rental_post_images" ("rentalPostId") `);
        await queryRunner.query(`CREATE TABLE "rental_posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "location" character varying NOT NULL, "roomType" character varying NOT NULL, "pricePerMonth" numeric(12,2) NOT NULL, "beds" integer NOT NULL DEFAULT '1', "baths" numeric(4,1) NOT NULL DEFAULT '1', "sqft" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_52b820c1e252e61b12b4626afdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_USER_ID" ON "rental_posts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_LOCATION" ON "rental_posts" ("location") `);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_ROOM_TYPE" ON "rental_posts" ("roomType") `);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_PRICE_PER_MONTH" ON "rental_posts" ("pricePerMonth") `);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_STATUS" ON "rental_posts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_RENTAL_POSTS_CREATED_AT" ON "rental_posts" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "codeHash" character varying NOT NULL, "type" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f2d4d7a2aa57ef199e61567db22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_VERIFICATION_TOKENS_EMAIL" ON "verification_tokens" ("email") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "ownerId" uuid, CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_CONVERSATIONS_USER_ID" ON "conversations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_CONVERSATIONS_OWNER_ID" ON "conversations" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "body" text NOT NULL, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "conversationId" uuid, "senderId" uuid, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_CONVERSATION_ID" ON "messages" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_SENDER_ID" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_CREATED_AT" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "propertyId" integer, CONSTRAINT "UQ_FAVORITES_USER_PROPERTY" UNIQUE ("userId", "propertyId"), CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_FAVORITES_USER_ID" ON "favorites" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_FAVORITES_PROPERTY_ID" ON "favorites" ("propertyId") `);
        await queryRunner.query(`CREATE TABLE "amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdOnDate" TIMESTAMP NOT NULL DEFAULT now(), "createdOnByUserId" character varying, "lastModifiedOnDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedByUserId" character varying, "deleteAt" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "UQ_8c5f9c7ff7e2174b53d4be10247" UNIQUE ("name"), CONSTRAINT "PK_c0777308847b3556086f2fb233e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "propertyId" integer, CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_BOOKINGS_USER_ID" ON "bookings" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOKINGS_PROPERTY_ID" ON "bookings" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOOKINGS_STATUS" ON "bookings" ("status") `);
        await queryRunner.query(`ALTER TABLE "medias" ADD CONSTRAINT "FK_0ca422a52c318ce86181dbf01ed" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medias" ADD CONSTRAINT "FK_056e28eb29a0f52a550e4b9f960" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "properties" ADD CONSTRAINT "FK_797b76e2d11a5bf755127d1aa67" FOREIGN KEY ("owner_id") REFERENCES "owners"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_2b1e1cd13649e9315b28b7f2f0c" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rental_post_images" ADD CONSTRAINT "FK_b98926ee33ea7d3a1f8862698cb" FOREIGN KEY ("rentalPostId") REFERENCES "rental_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rental_posts" ADD CONSTRAINT "FK_93c14cad3a5b20b270162e6ea5f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_a9b3b5d51da1c75242055338b59" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_58089e3bfdbdcf873faccfad4e9" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_e747534006c6e3c2f09939da60f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_39fd1b53d2b44d5bc1d766f9a2a" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_38a69a58a323647f2e75eb994de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_cf064476d403971270369232d80" FOREIGN KEY ("propertyId") REFERENCES "properties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_cf064476d403971270369232d80"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_38a69a58a323647f2e75eb994de"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_39fd1b53d2b44d5bc1d766f9a2a"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_e747534006c6e3c2f09939da60f"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_58089e3bfdbdcf873faccfad4e9"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_a9b3b5d51da1c75242055338b59"`);
        await queryRunner.query(`ALTER TABLE "rental_posts" DROP CONSTRAINT "FK_93c14cad3a5b20b270162e6ea5f"`);
        await queryRunner.query(`ALTER TABLE "rental_post_images" DROP CONSTRAINT "FK_b98926ee33ea7d3a1f8862698cb"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_2b1e1cd13649e9315b28b7f2f0c"`);
        await queryRunner.query(`ALTER TABLE "properties" DROP CONSTRAINT "FK_797b76e2d11a5bf755127d1aa67"`);
        await queryRunner.query(`ALTER TABLE "medias" DROP CONSTRAINT "FK_056e28eb29a0f52a550e4b9f960"`);
        await queryRunner.query(`ALTER TABLE "medias" DROP CONSTRAINT "FK_0ca422a52c318ce86181dbf01ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOKINGS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOKINGS_PROPERTY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOOKINGS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TABLE "amenities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FAVORITES_PROPERTY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FAVORITES_USER_ID"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_SENDER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_CONVERSATION_ID"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONVERSATIONS_OWNER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONVERSATIONS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_VERIFICATION_TOKENS_EMAIL"`);
        await queryRunner.query(`DROP TABLE "verification_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_PRICE_PER_MONTH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_ROOM_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_LOCATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POSTS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "rental_posts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RENTAL_POST_IMAGES_POST_ID"`);
        await queryRunner.query(`DROP TABLE "rental_post_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RESET_TOKENS_TOKEN_HASH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_RESET_TOKENS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SUBSCRIPTIONS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SUBSCRIPTIONS_USER_ID"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROPERTIES_LOCATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROPERTIES_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROPERTIES_PRICE_PER_MONTH"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROPERTIES_PRICE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROPERTIES_TITLE"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP TYPE "public"."properties_type_enum"`);
        await queryRunner.query(`DROP TABLE "owners"`);
        await queryRunner.query(`DROP TABLE "medias"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_LOCATION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
